"""Update field to sane values

Revision ID: 8d7574adda56
Revises: 96754527b608
Create Date: 2020-04-11 13:26:15.971124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d7574adda56'
down_revision = '96754527b608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reference', 'refAuthors',
               existing_type=mysql.VARCHAR(length=4096),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('reference', 'refDoi',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('reference', 'refTitle',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('result', 'resultAuthors',
               existing_type=mysql.VARCHAR(length=4096),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('result', 'resultComment',
               existing_type=mysql.VARCHAR(length=8192),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('result', 'resultDoi',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('result', 'resultTitle',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('result', 'time',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('result', 'tool',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('result', 'type',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('result', 'value',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('submission', 'authors',
               existing_type=mysql.VARCHAR(length=4096),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('submission', 'description',
               existing_type=mysql.VARCHAR(length=4096),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('submission', 'doi',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('submission', 'imageFileURL',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('submission', 'modelName',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('submission', 'origPaperTitle',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('submission', 'yourEmail',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('variant', 'dftFileURL',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('variant', 'varAuthors',
               existing_type=mysql.VARCHAR(length=4096),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('variant', 'varDescription',
               existing_type=mysql.VARCHAR(length=4096),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('variant', 'varDoi',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('variant', 'varName',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('variant', 'varTitle',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variant', 'varTitle',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('variant', 'varName',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('variant', 'varDoi',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('variant', 'varDescription',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=4096),
               existing_nullable=True)
    op.alter_column('variant', 'varAuthors',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=4096),
               existing_nullable=True)
    op.alter_column('variant', 'dftFileURL',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('submission', 'yourEmail',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('submission', 'origPaperTitle',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('submission', 'modelName',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('submission', 'imageFileURL',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('submission', 'doi',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('submission', 'description',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=4096),
               existing_nullable=True)
    op.alter_column('submission', 'authors',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=4096),
               existing_nullable=True)
    op.alter_column('result', 'value',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('result', 'type',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('result', 'tool',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('result', 'time',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('result', 'resultTitle',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('result', 'resultDoi',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('result', 'resultComment',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=8192),
               existing_nullable=True)
    op.alter_column('result', 'resultAuthors',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=4096),
               existing_nullable=True)
    op.alter_column('reference', 'refTitle',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('reference', 'refDoi',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('reference', 'refAuthors',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=4096),
               existing_nullable=True)
    # ### end Alembic commands ###
