"""Initial db for trees

Revision ID: 96754527b608
Revises: 
Create Date: 2020-04-11 12:30:33.691266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96754527b608'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference',
    sa.Column('refId', sa.Integer(), nullable=False),
    sa.Column('refTitle', sa.String(length=1024), nullable=True),
    sa.Column('refAuthors', sa.String(length=4096), nullable=True),
    sa.Column('refDoi', sa.String(length=2048), nullable=True),
    sa.Column('refYear', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('refId')
    )
    op.create_table('result',
    sa.Column('resId', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=1024), nullable=True),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('time', sa.String(length=1024), nullable=True),
    sa.Column('tool', sa.String(length=1024), nullable=True),
    sa.Column('resultTitle', sa.String(length=1024), nullable=True),
    sa.Column('resultAuthors', sa.String(length=4096), nullable=True),
    sa.Column('resultDoi', sa.String(length=2048), nullable=True),
    sa.Column('varYear', sa.Integer(), nullable=True),
    sa.Column('resultComment', sa.String(length=8192), nullable=True),
    sa.PrimaryKeyConstraint('resId')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yourName', sa.String(length=256), nullable=True),
    sa.Column('yourEmail', sa.String(length=512), nullable=True),
    sa.Column('modelName', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('imageFileURL', sa.String(length=2048), nullable=True),
    sa.Column('origPaperTitle', sa.String(length=1024), nullable=True),
    sa.Column('authors', sa.String(length=4096), nullable=True),
    sa.Column('doi', sa.String(length=2048), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variant',
    sa.Column('varId', sa.Integer(), nullable=False),
    sa.Column('dftFileURL', sa.String(length=2048), nullable=True),
    sa.Column('varName', sa.String(length=1024), nullable=True),
    sa.Column('varDescription', sa.String(length=4096), nullable=True),
    sa.Column('varTitle', sa.String(length=1024), nullable=True),
    sa.Column('varAuthors', sa.String(length=4096), nullable=True),
    sa.Column('varDoi', sa.String(length=2048), nullable=True),
    sa.Column('varYear', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('varId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant')
    op.drop_table('submission')
    op.drop_table('result')
    op.drop_table('reference')
    # ### end Alembic commands ###
