"""empty message

Revision ID: f54ff3d62331
Revises: 
Create Date: 2020-04-22 15:48:16.765111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54ff3d62331'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yourName', sa.String(length=256), nullable=False),
    sa.Column('yourEmail', sa.String(length=128), nullable=False),
    sa.Column('modelName', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('imageFileURL', sa.String(length=256), nullable=True),
    sa.Column('origPaperTitle', sa.String(length=256), nullable=False),
    sa.Column('authors', sa.String(length=2048), nullable=False),
    sa.Column('doi', sa.String(length=256), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('dateAdded', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference',
    sa.Column('refId', sa.Integer(), nullable=False),
    sa.Column('refTitle', sa.String(length=256), nullable=False),
    sa.Column('refAuthors', sa.String(length=2048), nullable=False),
    sa.Column('refDoi', sa.String(length=256), nullable=False),
    sa.Column('refYear', sa.Integer(), nullable=False),
    sa.Column('sub', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('refId')
    )
    op.create_table('variant',
    sa.Column('varId', sa.Integer(), nullable=False),
    sa.Column('dftFileURL', sa.String(length=256), nullable=False),
    sa.Column('varName', sa.String(length=256), nullable=False),
    sa.Column('varDescription', sa.String(length=2048), nullable=True),
    sa.Column('varTitle', sa.String(length=256), nullable=False),
    sa.Column('varAuthors', sa.String(length=2048), nullable=False),
    sa.Column('varDoi', sa.String(length=256), nullable=False),
    sa.Column('varYear', sa.Integer(), nullable=False),
    sa.Column('sub', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('varId')
    )
    op.create_table('result',
    sa.Column('resId', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('time', sa.String(length=128), nullable=False),
    sa.Column('tool', sa.String(length=256), nullable=False),
    sa.Column('resultTitle', sa.String(length=256), nullable=False),
    sa.Column('resultAuthors', sa.String(length=2048), nullable=False),
    sa.Column('resultDoi', sa.String(length=256), nullable=False),
    sa.Column('resYear', sa.Integer(), nullable=False),
    sa.Column('resultComment', sa.String(length=2048), nullable=True),
    sa.Column('var', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['var'], ['variant.varId'], ),
    sa.PrimaryKeyConstraint('resId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('variant')
    op.drop_table('reference')
    op.drop_table('submission')
    # ### end Alembic commands ###
